#!/usr/bin/env bash
# Per-boot startup for the AnimaBoard Cloud Agent environment.
# Starts the Docker daemon (systemd is not PID 1 here, so it must be launched
# manually), brings up the local Supabase stack, and materializes the local
# .env. Idempotent: safe to run when things are already up.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "==> [start] Ensuring Docker daemon is running"
if ! docker info >/dev/null 2>&1; then
  # Nested container: enable overlay/bridge networking prerequisites.
  sudo modprobe br_netfilter 2>/dev/null || true
  echo "==> [start] Launching dockerd"
  sudo nohup dockerd >/tmp/dockerd.log 2>&1 &
  for i in $(seq 1 30); do
    if sudo docker info >/dev/null 2>&1; then break; fi
    sleep 1
  done
fi
# Make the socket usable by the current (non-root) user.
sudo chmod 666 /var/run/docker.sock || true
docker info >/dev/null 2>&1 || { echo "!! [start] Docker daemon failed to start"; tail -n 30 /tmp/dockerd.log || true; exit 1; }
echo "==> [start] Docker is up"

# Inter-container traffic on a user-defined bridge must bypass netfilter,
# otherwise Supabase service containers cannot reach the Postgres container
# in this nested environment.
sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 >/dev/null 2>&1 || true
sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=0 >/dev/null 2>&1 || true

echo "==> [start] Starting local Supabase stack (excluding edge-runtime)"
# supabase start is idempotent: a no-op (exit 0) when the stack is already up.
# edge-runtime is excluded because its Deno health check fails in this nested
# container and the app does not use edge functions.
npx --yes supabase start -x edge-runtime

echo "==> [start] Writing .env from supabase status"
# The local Supabase service_role key is a well-known fixed dev key; regenerate
# .env every boot so SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY always match.
SUPA_ENV="$(npx --yes supabase status -o env 2>/dev/null)"
SERVICE_ROLE_KEY="$(printf '%s\n' "$SUPA_ENV" | sed -n 's/^SERVICE_ROLE_KEY="\(.*\)"$/\1/p')"
API_URL="$(printf '%s\n' "$SUPA_ENV" | sed -n 's/^API_URL="\(.*\)"$/\1/p')"
API_URL="${API_URL:-http://127.0.0.1:55221}"

cat > "$ROOT/.env" <<ENV
# Auto-generated by .cursor/start.sh — do not commit.
PORT=3000
NODE_ENV=development

SUPABASE_URL=${API_URL}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# External integrations — placeholder creds; their syncs will fail until real
# BoondManager / Pennylane credentials are supplied.
BOOND_API_URL=https://ui.boondmanager.com/api
BOOND_EMAIL=your_email@example.com
BOOND_PASSWORD=your_password_here
PENNYLANE_API_URL=https://app.pennylane.com/api/external/v2
PENNYLANE_API_KEY=your_api_token_here
ENV

echo "==> [start] Ready. Supabase API at ${API_URL}"
